services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  account_db:
    image: postgres:16
    container_name: account_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_db
    ports:
      - "5432:5432"
    volumes:
      - account_db_data:/var/lib/postgresql/data
      - ./services/account-service/db/migrations/000001_create_accounts_table.up.sql:/docker-entrypoint-initdb.d/000001_create_accounts_table.up.sql

  transaction_db:
    image: postgres:16
    container_name: transaction_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transaction_db
    ports:
      - "5433:5432"
    volumes:
      - transaction_db_data:/var/lib/postgresql/data
      - ./services/transaction-service/db/migrations/000001_create_transaction_tables.up.sql:/docker-entrypoint-initdb.d/000001_create_transaction_tables.up.sql

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - account_db
      - transaction_db
    restart: unless-stopped

  lgtm:
    image: grafana/otel-lgtm
    container_name: lgtm
    ports:
      - "3000:3000"   # Grafana
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - lgtm_data:/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
  account_db_data:
  transaction_db_data:
  lgtm_data: